version: '3.8'
services:
  app:
    image: contact-mailer-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - TO_EMAIL=${TO_EMAIL}
      - PORT=${APP_PORT}
    network_mode: host